# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://dimasprasetya.web.id
title: DimasPrasetya.Web.Id
subtitle: Read, Research, Understand, Share
author: Dimas Prasetya
simple_search: https://www.google.com/search
description: Didedikasikan untuk berbagi ilmu seputar IT meliputi programming web, mobile, desktop, dan sebagai catatan agar ilmu yang sudah didapat bisa bermanfaat bagi orang lain yang membutuhkan.
keywords: programming, pemrograman, web, web programming, mobile programming, android, java, algoritma, IT, security, design

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "ordinal"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /atom.xml
subscribe_email:
# RSS feeds can list your email address if you like
email:

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root: /
permalink: /blog/:year/:month/:day/:title/
source: source
destination: public
plugins: plugins
code_dir: downloads/code
category_dir: blog/categories
markdown: rdiscount
rdiscount:
  extensions:
    - autolink
    - footnotes
    - smart
highlighter: pygments # default python pygments have been replaced by pygments.rb

paginate: 8          # Posts per page on the blog index
paginate_path: "posts/:num"  # Directory base for pagination URLs eg. /posts/2/
recent_posts: 5       # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles
excerpt_separator: "<!--more-->"

titlecase: true       # Converts page and post titles to titlecase

# list each of the sidebar modules you want to include, in the order you want them to appear.
# To add custom asides, create files in /source/_includes/custom/asides/ and add them to the list like 'custom/asides/custom_aside_name.html'
default_asides: [ asides/recent_posts.html, custom/asides/category_list.html, custom/asides/monthly_archive.html, custom/asides/about.html, asides/googleplus.html]

# Each layout uses the default asides, but they can have their own asides instead. Simply uncomment the lines below
# and add an array with the asides you want to use.
# blog_index_asides:
# post_asides:
# page_asides:

# Relate Post
# lsi: true

popular_posts_count: 5      # Posts in the sidebar Popular Posts section

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Github repositories
github_user: dimas-prasetya
github_repo_count: 0
github_show_profile_link: true
github_skip_forks: true

# Twitter
twitter_user: D_Mas95
twitter_tweet_button: true

# Google +1
google_plus_one: true
google_plus_one_size: medium

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
googleplus_user: 109095740331831712177
googleplus_hidden: false

# Pinboard
pinboard_user:
pinboard_count: 3

# Delicious
delicious_user:
delicious_count: 3

# Disqus Comments
disqus_short_name: dimasprasetyawebid
disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id: UA-51165053-2

# Facebook Like
facebook_like: true

# Facebook Profile
facebook_user: AndroCyber

# --------------- #
# Monthly Archive #
# --------------- #

# Show the number of posts
monthly_archive_count: true

monthly_archive_open: latest

# Month View Format
monthly_archive_format: January

# monthly_title_prefix: Archive:

monthly_format: January
